#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <malloc.h>
#include <math.h>
#include <gccore.h>
#include <string.h>

#include <GL/glut.h>

#include "lua_util.h"

BINDFUNC(void, glutInit, int *, char **)
BINDFUNC(void, glutInitDisplayMode, unsigned int)
//BINDFUNC(void, glutInitDisplayString, const char *)
//BINDFUNC(void, glutInitWindowPosition, int, int)
BINDFUNC(void, glutInitWindowSize, int, int)
BINDFUNC(void, glutMainLoop)
BINDFUNC(int, glutCreateWindow, const char *)
//BINDFUNC(int, glutCreateSubWindow, int, int, int, int, int)
//BINDFUNC(void, glutDestroyWindow, int)
//BINDFUNC(void, glutPostRedisplay)
//BINDFUNC(void, glutPostWindowRedisplay, int)
BINDFUNC(void, glutSwapBuffers)
//BINDFUNC(int, glutGetWindow)
//BINDFUNC(void, glutSetWindow, int)
//BINDFUNC(void, glutSetWindowTitle, const char *)
//BINDFUNC(void, glutSetIconTitle, const char *)
//BINDFUNC(void, glutPositionWindow, int, int)
//BINDFUNC(void, glutReshapeWindow, int, int)
//BINDFUNC(void, glutPopWindow)
//BINDFUNC(void, glutPushWindow)
//BINDFUNC(void, glutIconifyWindow)
//BINDFUNC(void, glutShowWindow)
//BINDFUNC(void, glutHideWindow)
//BINDFUNC(void, glutFullScreen)
//BINDFUNC(void, glutSetCursor, int)
//BINDFUNC(void, glutWarpPointer, int, int)
//BINDFUNC(void, glutEstablishOverlay)
//BINDFUNC(void, glutRemoveOverlay)
//BINDFUNC(void, glutUseLayer, GLenum)
//BINDFUNC(void, glutPostOverlayRedisplay)
//BINDFUNC(void, glutPostWindowOverlayRedisplay, int)
//BINDFUNC(void, glutShowOverlay)
//BINDFUNC(void, glutHideOverlay)
//BINDFUNC(void, glutDestroyMenu, int)
//BINDFUNC(int, glutGetMenu)
//BINDFUNC(void, glutSetMenu, int)
//BINDFUNC(void, glutAddMenuEntry, const char *, int)
//BINDFUNC(void, glutAddSubMenu, const char *, int)
//BINDFUNC(void, glutChangeToMenuEntry, int, const char *, int)
//BINDFUNC(void, glutChangeToSubMenu, int, const char *, int)
//BINDFUNC(void, glutRemoveMenuItem, int)
//BINDFUNC(void, glutAttachMenu, int)
//BINDFUNC(void, glutDetachMenu, int)
//BINDFUNC(void, glutSetColor, int, GLfloat, GLfloat, GLfloat)
//BINDFUNC(GLfloat, glutGetColor, int, int)
//BINDFUNC(void, glutCopyColormap, int)
BINDFUNC(int, glutGet, GLenum)
//BINDFUNC(int, glutDeviceGet, GLenum)
BINDFUNC(int, glutExtensionSupported, const char *)
//BINDFUNC(int, glutGetModifiers)
//BINDFUNC(int, glutLayerGet, GLenum)
BINDFUNC(void, glutBitmapCharacter, void *, int)
BINDFUNC(int, glutBitmapWidth, void *, int)
BINDFUNC(void, glutStrokeCharacter, void *, int)
BINDFUNC(int, glutStrokeWidth, void *, int)
BINDFUNC(int, glutBitmapLength, void *, const unsigned char *)
BINDFUNC(int, glutStrokeLength, void *, const unsigned char *)
BINDFUNC(void, glutWireSphere, GLdouble, GLint, GLint)
BINDFUNC(void, glutSolidSphere, GLdouble, GLint, GLint)
BINDFUNC(void, glutWireCone, GLdouble, GLdouble, GLint, GLint)
BINDFUNC(void, glutSolidCone, GLdouble, GLdouble, GLint, GLint)
BINDFUNC(void, glutWireCube, GLdouble)
BINDFUNC(void, glutSolidCube, GLdouble)
BINDFUNC(void, glutWireTorus, GLdouble, GLdouble, GLint, GLint)
BINDFUNC(void, glutSolidTorus, GLdouble, GLdouble, GLint, GLint)
BINDFUNC(void, glutWireDodecahedron)
BINDFUNC(void, glutSolidDodecahedron)
BINDFUNC(void, glutWireTeapot, GLdouble)
BINDFUNC(void, glutSolidTeapot, GLdouble)
BINDFUNC(void, glutWireOctahedron)
BINDFUNC(void, glutSolidOctahedron)
BINDFUNC(void, glutWireTetrahedron)
BINDFUNC(void, glutSolidTetrahedron)
BINDFUNC(void, glutWireIcosahedron)
BINDFUNC(void, glutSolidIcosahedron)
//BINDFUNC(int, glutVideoResizeGet, GLenum)
//BINDFUNC(void, glutSetupVideoResizing)
//BINDFUNC(void, glutStopVideoResizing)
//BINDFUNC(void, glutVideoResize, int, int, int, int)
//BINDFUNC(void, glutVideoPan, int, int, int, int)
BINDFUNC(void, glutReportErrors)
//BINDFUNC(void, glutIgnoreKeyRepeat, int)
//BINDFUNC(void, glutSetKeyRepeat, int)
//BINDFUNC(void, glutForceJoystickFunc)
//BINDFUNC(void, glutGameModeString, const char *)
//BINDFUNC(int, glutEnterGameMode)
//BINDFUNC(void, glutLeaveGameMode)
//BINDFUNC(int, glutGameModeGet, GLenum)

void init_binding_GLUT(lua_State *L) {
	int ffi = lua_gettop(L);

	FFI_CDEF_FILE("include/GLUT_types.h");
	BEGIN_PACKAGE(glut)

BINDNAME(glutInit)
BINDNAME(glutInitDisplayMode)
//BINDNAME(glutInitDisplayString)
//BINDNAME(glutInitWindowPosition)
BINDNAME(glutInitWindowSize)
BINDNAME(glutMainLoop)
BINDNAME(glutCreateWindow)
//BINDNAME(glutCreateSubWindow)
//BINDNAME(glutDestroyWindow)
//BINDNAME(glutPostRedisplay)
//BINDNAME(glutPostWindowRedisplay)
BINDNAME(glutSwapBuffers)
//BINDNAME(glutGetWindow)
//BINDNAME(glutSetWindow)
//BINDNAME(glutSetWindowTitle)
//BINDNAME(glutSetIconTitle)
//BINDNAME(glutPositionWindow)
//BINDNAME(glutReshapeWindow)
//BINDNAME(glutPopWindow)
//BINDNAME(glutPushWindow)
//BINDNAME(glutIconifyWindow)
//BINDNAME(glutShowWindow)
//BINDNAME(glutHideWindow)
//BINDNAME(glutFullScreen)
//BINDNAME(glutSetCursor)
//BINDNAME(glutWarpPointer)
//BINDNAME(glutEstablishOverlay)
//BINDNAME(glutRemoveOverlay)
//BINDNAME(glutUseLayer)
//BINDNAME(glutPostOverlayRedisplay)
//BINDNAME(glutPostWindowOverlayRedisplay)
//BINDNAME(glutShowOverlay)
//BINDNAME(glutHideOverlay)
//BINDNAME(glutDestroyMenu)
//BINDNAME(glutGetMenu)
//BINDNAME(glutSetMenu)
//BINDNAME(glutAddMenuEntry)
//BINDNAME(glutAddSubMenu)
//BINDNAME(glutChangeToMenuEntry)
//BINDNAME(glutChangeToSubMenu)
//BINDNAME(glutRemoveMenuItem)
//BINDNAME(glutAttachMenu)
//BINDNAME(glutDetachMenu)
//BINDNAME(glutSetColor)
//BINDNAME(glutGetColor)
//BINDNAME(glutCopyColormap)
BINDNAME(glutGet)
//BINDNAME(glutDeviceGet)
BINDNAME(glutExtensionSupported)
//BINDNAME(glutGetModifiers)
//BINDNAME(glutLayerGet)
BINDNAME(glutBitmapCharacter)
BINDNAME(glutBitmapWidth)
BINDNAME(glutStrokeCharacter)
BINDNAME(glutStrokeWidth)
BINDNAME(glutBitmapLength)
BINDNAME(glutStrokeLength)
BINDNAME(glutWireSphere)
BINDNAME(glutSolidSphere)
BINDNAME(glutWireCone)
BINDNAME(glutSolidCone)
BINDNAME(glutWireCube)
BINDNAME(glutSolidCube)
BINDNAME(glutWireTorus)
BINDNAME(glutSolidTorus)
BINDNAME(glutWireDodecahedron)
BINDNAME(glutSolidDodecahedron)
BINDNAME(glutWireTeapot)
BINDNAME(glutSolidTeapot)
BINDNAME(glutWireOctahedron)
BINDNAME(glutSolidOctahedron)
BINDNAME(glutWireTetrahedron)
BINDNAME(glutSolidTetrahedron)
BINDNAME(glutWireIcosahedron)
BINDNAME(glutSolidIcosahedron)
//BINDNAME(glutVideoResizeGet)
//BINDNAME(glutSetupVideoResizing)
//BINDNAME(glutStopVideoResizing)
//BINDNAME(glutVideoResize)
//BINDNAME(glutVideoPan)
BINDNAME(glutReportErrors)
//BINDNAME(glutIgnoreKeyRepeat)
//BINDNAME(glutSetKeyRepeat)
//BINDNAME(glutForceJoystickFunc)
//BINDNAME(glutGameModeString)
//BINDNAME(glutEnterGameMode)
//BINDNAME(glutLeaveGameMode)
//BINDNAME(glutGameModeGet)

	END_PACKAGE()

}
